apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nabilhjeiji/backend-healthcare  # Change this to your built backend image
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "True"
            - name: DATABASE_URL
              value: "mysql://nabil:hjeiji@db:3306/HealthCare"  # Adjust if needed
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
