apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nabilhjeiji/healthcare  # Replace with your built Angular image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: healthcare
spec:
  type: NodePort  # Or LoadBalancer if you're using a cloud provider
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # Optional: specify if using NodePort
  selector:
    app: frontend
